### ISSUE TITLE
DhcpClient:IPv6 disabled but not really

### ISSUE THREAD

**Issue by socr2121** [dsccommunity/NetworkingDsc#334]
**Details of the scenario you tried and the problem that is occurring:**
I am trying to change IPV6 to disabled. It runs fine and says that it checks IPV6 on Ethernet and skips setting to disable. It runs clean but when I go and check get-netadapterbinding for ms_tcpip6, it is still enabled.
**The DSC configuration that is using the resource (as detailed as possible):**
Config only testing this one feature.
**Version of the Operating System and PowerShell the DSC Target Node is running:**
W2K12R2/WMF5.1
**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Newest version of NetworkingDsc and tried xNetworking 5.7.0.0

**Comment by kewalaka** [comment]
I think the approach to disable ipv6 is wrong, unless the advice here is no longer correct:

https://support.microsoft.com/en-us/help/929852/guidance-for-configuring-ipv6-in-windows-for-advanced-users

The correct approach according to the above article is :

```
reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters" /v DisabledComponents /t REG_DWORD /d 0xFF /f
```

Note that this then does not actually disable the binding which means "IPv6" is still ticked in the UI, so it may be perceived that this does not work, but you can verify it by looking at the output of ipconfig.

Suggest that perhaps we need to find a different home for this ?  NetDisableComponents?

**Comment by PlagueHO** [comment]
If we're trying to disable IPv6 completely across the entire OS, then NetDisableComponents would be a good name for it and would be a useful resource. 

I think this issue is specifically talking about disabling DHCP on IPv6 on a specific adapter though, rather than disabling IPv6 completely.

Can you confirm @socr2121 ?

**Comment by phbits** [comment]
@PlagueHO - this issue should be closed since the following changelog entry shows this functionality no longer exists.

> [7.0.0.0] - 2019-02-20
> - MSFT_DhcpClient:
>   - BREAKING CHANGE: Resource has been deprecated and replaced by `Dhcp`
>     parameter in MSFT_NetIPInterface.

Regarding `DisabledComponents`, @PlagueHO  is right that this setting impacts the entire OS. IMO, this doesn't make it a good fit for NetworkingDsc. A better approach would be to apply it as a registry setting via [PSDscResources](https://github.com/PowerShell/PSDscResources).

`NetAdapterBinding` is a separate configuration and will not be changed regardless of how DHCP is configured on a network interface or whether `DisabledComponents` is configured.
