### ISSUE TITLE
NetAdapterAdvancedProperty: Set-TargetResource

### ISSUE THREAD

**Issue by phbits** [dsccommunity/NetworkingDsc#485]
When invoking `Set-TargetResource` for DSC_NetAdapterAdvancedProperty, there appears to be unnecessary code and would like confirmation that this is the case.

My understanding is that `Set-TargetResource` should only be invoked when `Test-TargetResource` fails. At which point the desired configuration is passed to `Set-TargetResource` for it to "Stamp" the configuration change.

However, in this case the logic flow goes:

Invoke `Set-TargetResource`
Get configuration by invoking `Get-NetAdapterAdvancedProperty`
Verify the above command returned a value
Compare if desired value is the same as value returned by `Get-NetAdapterAdvancedProperty`
If above is different, set the value.

Again, this all seems unnecessary and I don't understand why it was included. Everything those checks were trying to achieve should have been caught earlier in the process. `Get-NetAdapterAdvancedProperty` failing to return an object should have been identified via `Get-TargetResource`. Then `Test-TargetResource` should have identified it as not being in the desired state. The only time when additional checks should occur within `Set-TargetResource` is when wildcards are allowed such as the case with DSC_NetBios. For this requires iterating through adapters to find the one needing to be configured. That being said, `DSC_NetAdapterAdvancedProperty` doesn't leverage wildcards.

**Comment by PlagueHO** [comment]
That is a good question @phbits. The DSC LCM does indeed behave like that -only calling `Set-TargetResource` if `Test-TargetResource` returns `$false`.

However, these resources are also used by other IaC platforms (Chef, Puppet, Ansible) as well as the new `Invoke-DscResource` cmdlet. These are not guaranteed to first call `Test-TargetResource` (they most likely do, but no promise). Therefore, `Set-TargetResource` must behave in an idempotent fashion and only make changes if they are necessary.

That said, not every resource behaves like this - even if it should.

As for the wildcards, to be honest: we shouldn't really allow them because they are problematic for the following reasons:
1. They allow for configurations that may be partially in-state.
2. They enable configurations that will "flap" because the "key" does no represent a single unique resource.

We've previously allowed wild card support into resources, but in hind sight this was a mistake and has resulted in more problems than the edge cases that the solved. So, we'll likely be backing out wild card support in these resources.

**Comment by phbits** [comment]
@PlagueHO Thanks for the very thorough response! Surprised to learn that other IaC platforms choose not to adopt the same functionality as LCM. 😕 Good to know.

Also, THANK YOU for working with me on those PRs. Much appreciated!

On a related note, the catalyst for my involvement in this module is I got tired creating DSC configurations by hand. So I built a PowerShell module, [DscBaseline](https://github.com/phbits/DscBaseline) which essentially does a Get-TargetResource and builds a DSC configuration file. That's what lead me to finding the issues addressed by my PRs.
